// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"review-task/internal/biz"
	"review-task/internal/conf"
	"review-task/internal/data"
	"review-task/internal/server"
	"review-task/internal/service"
	"review-task/internal/task"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, kafka *conf.Kafka, elasticsearch *conf.Elasticsearch, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	greeterRepo := data.NewGreeterRepo(dataData, logger)
	greeterUsecase := biz.NewGreeterUsecase(greeterRepo, logger)
	greeterService := service.NewGreeterService(greeterUsecase)
	grpcServer := server.NewGRPCServer(confServer, greeterService, logger)
	httpServer := server.NewHTTPServer(confServer, greeterService, logger)
	reader := task.NewKafkaReader(kafka)
	esClient, err := task.NewESClient(elasticsearch)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	taskWorker := task.NewTaskWorker(reader, esClient, logger)
	app := newApp(logger, grpcServer, httpServer, taskWorker)
	return app, func() {
		cleanup()
	}, nil
}
